version: '2'

services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ../conf/nginx/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always

  epicollect-frontend:
    depends_on:
      - reverse-proxy
    image: epicollect/frontend:latest
    restart: always

  epicollect-backend:
    depends_on:
      - reverse-proxy
    image: epicollect/backend:latest
    restart: always